zuul:
  routes:
    service-a:
      path: /service-a/**
      serviceId: service-a
    service-b:
      path: /service-b/**
      serviceId: service-b
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 30000